### PR TITLE
Init options

### PR DESCRIPTION
**Pull request by tuahk**
I added support and chefspecs for bluepill. I think this is a good structure where we could easily start adding more init options. It follows pretty closely nginx cookbook.

I all so moved flag generation in to libraries/prometheus_helper.rb

### CODE REVIEW

**Comment by rayrod2030** [comment]
Changes look good but I don't see where bluepill is logging for this service.  I feel like we should set a default logging location by default for any init service that we handle and allow the user to configure if they prefer to log somewhere else.  Runit currently logs to it's default runit location but perhaps we can standardize on logging to /var/log/prometheus/prometheus.log for all init styles?

**Comment by tuahk** [comment]
Ok, by default bluepill uses syslog and logging location is in /var/log/bluepill.log. I could either change that location or use only log file as they did in nginx cookbook, any preference on this? Maybe all so make an attribute that defines logging location

**Comment by rayrod2030** [comment]
@tuahk Yup probably makes sense to set stdout as it's done in nginx cookbook and yeah probably set up a log location attribute.  The other init styles can be based on that attribute where needed.

**Comment by rayrod2030** [comment]
`process.stdout             = process.stderr = "<%= node['prometheus']['log_dir'] %>/nginx.log"` would work nicely.

**Comment by tuahk** [comment]
Wow, I don't know what my night brain was thinking. I added directory resource for prometheus logs and added that line you suggested to pill.erb. I did remove log_file attribute from pill.erb so bluepill logs are in default location.

**Pull request merged**
