### PR TITLE
Rearrange recipes and start of precompiled binary support

### PR DESCRIPTION
**Pull request by tuahk**
The purpose of this PR is to suggest a new way to arrange our recipes.

- Moved directories and user resources to default.rb
- Moved config template to default.rb (As ewr did in his PR)
- Moved init and prometheus service to init.rb recipe which is included in default.

This will obviously break chefspecs but I just wanted to run this through you guys first.
If I get green light for this then I start making changes to chefspec and update this PR to include those.

This PR also starts work on binary.rb and adds some serverspec tests for it.

### CODE REVIEW

**Comment by rayrod2030** [comment]
This is a nice refactor.  I would consider renaming recipes/init.rb to recipes/service.rb to use a more generic term.

**Comment by rayrod2030** [comment]
:+1:

**Comment by tuahk** [comment]
I renamed source_spec.rb to default_spec.rb and put all the tests in there.

It would be cleaner if we had separate spec files for each recipe but chefspec doesn’t find prometheus service from other recipes since we include all to default. There probably is a way around this but I don't yet know about it.

**Comment by tuahk** [comment]
Sorry about the rubocop commits but for some reason rubocop doesn't complain about them on my computer. I have to look in to it.

**Pull request merged**
