### PR TITLE
Update binary.rb

### PR DESCRIPTION
**Pull request by tuahk**
Added support for different tar files and made the changes that were suggested by ewr.

### CODE REVIEW

**Comment by rayrod2030** [comment]
These changes look good.  I take it that these changes will upgrade the running prometheus binary if the user defines a newer version in the attributes?

**Comment by tuahk** [comment]
Yup, if you change version attribute to something that your node hasn't yet used, then it will extract that file and update binary. At least to my understanding and testing.

However, if you want to change back to version you used to use, then there already exists a tar file and extract does not get notified, so binary stays in previous version. Should it be possible to change back to previous version?

I actually think we might want to start using this cookbook https://github.com/burtlo/ark to handle binary installation?

**Comment by rayrod2030** [comment]
Yes absolutely I always forget about ark.  It's definitely the way to go there.

**Comment by tuahk** [comment]
Great! I'll make other PR today or tomorrow which uses ark.

**Pull request closed without merging**
