### PR TITLE
Start using ark to handle binary installation

### PR DESCRIPTION
**Pull request by tuahk**
First suggestion for binary.rb with ark. 
No chefspecs yet.

### CODE REVIEW

**Comment by rayrod2030** [comment]
This look fine.  What else do you think this would need other than some specs?

**Comment by tuahk** [comment]
Hmm.. I don't know. I think it's ok as it is but let me know if you have some ideas?

**Comment by tuahk** [comment]
I added custom matcher for ark_put. Arks next release should include packaged custom matcher so it's only temporary.

**Comment by rayrod2030** [comment]
Looks great.  I'd like to merge if you are ok with it.

**Comment by tuahk** [comment]
Yeah, just go ahead

**Pull request merged**
