### PR TITLE
Allow external management of prometheus.conf

### PR DESCRIPTION
**Pull request by ewr**
So just after we merged #22, allowing easier configuration, I'd now like a change that takes this cookbook out of the config business. 

Context is in prometheus/prometheus#608. Basically the existing service discovery isn't quite doing what I need it to because of a detail in how Consul implements SRV lookups. Until we get that sorted I plan to use [consul-template](https://github.com/hashicorp/consul-template) to make sure all my nodes get written into the config correctly.

To do that, though, I need this cookbook to not care that my external process is writing a new config file. This seems like a fairly normal case (a wrapper cookbook that is opinionated about how the config gets created), so I think both config cases help expand what the cookbook can do.

### CODE REVIEW

**Comment by rayrod2030** [comment]
I fixed that issue with that spec so if you merge master your PR should pass.

**Comment by rayrod2030** [comment]
And as far as this change I'm all for it.  I'll be spending some time on the README to explain all of these options for the next release.

**Comment by ewr** [comment]
Cool. Did the merge, and I've updated our wrapper cookbook to start using this successfully.

**Comment by ewr** [comment]
Thanks! :+1:

**Pull request merged**
